import { Golos_Text, Unbounded } from "next/font/google";

/**
 * The English page's fonts — the same two families without the Cyrillic subset.
 *
 * `next/font` emits a `<link rel="preload">` for every subset a declaration asks
 * for, `unicode-range` notwithstanding: it cannot know which glyphs a page will
 * use. One shared `subsets: ["cyrillic", "latin"]` therefore made `/en` preload
 * two Cyrillic woff2 files (31,460 + 22,028 = 53,488 B) at the highest priority,
 * ahead of the two it does need.
 *
 * The split has to be at module level, and that is why this is a file and not a
 * `Record<Locale, …>` beside the other pair: the preload list is collected per
 * route from the `next/font` calls in its module graph, so declaring both pairs
 * in one module and choosing between them at render time still preloads all
 * four. Each locale's layout imports exactly one of these two modules.
 *
 * **The split alone is not enough under Turbopack, so the preloads are emitted
 * by hand.** Measured on Next 16.2.12: `next build --webpack` writes a per-route
 * `next-font-manifest.json` and the split lands on its own, while `next build`
 * (Turbopack, the default and what this app ships with) writes the project-wide
 * UNION of every declaration under every route key — `/`, `/en` and even
 * `_not-found` all listed all four files. Nothing arrangeable in these two
 * modules changes that: the union is by construction the RU set.
 *
 * So every declaration here and in `fonts-cyrillic.ts` passes `preload: false`,
 * which suppresses the automatic emission while still self-hosting the font and
 * writing the `@font-face` rules, and `RootHtml` emits `FONT_PRELOADS` instead.
 * The result is exact rather than approximate: `/en` preloads the two Latin
 * files and `/` the four it draws from, on either builder.
 *
 * `FONT_PRELOADS` is generated by `scripts/sync-font-preloads.mjs` out of the
 * build's own `@font-face` rules — the file names are content-hashed and a
 * hardcoded one would go stale into a top-priority 404. That script's header
 * explains how it is kept honest; it runs in `npm test` and again after
 * `next build`.
 */
const display = Unbounded({
  subsets: ["latin"],
  weight: ["500", "700", "900"],
  variable: "--font-unbounded",
  preload: false,
});

const sans = Golos_Text({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-golos",
  preload: false,
});

export const FONT_VARIABLES = `${display.variable} ${sans.variable}`;

export const FONT_PRELOADS: readonly string[] = [
  // sync-font-preloads:begin ↓ generated by scripts/sync-font-preloads.mjs
  "/_next/static/media/b4a06a523f527a0e-s.3psl0_mnhzy2y.woff2",
  "/_next/static/media/b59689b1142d37ce-s.1bk8_xp319hr4.woff2",
  // sync-font-preloads:end ↑
];
