import { Golos_Text, Unbounded } from "next/font/google";

/**
 * The Russian page's fonts. See `fonts-latin.ts` for why there are two of these
 * files rather than one lookup table — the split has to be at module level — and
 * for why `preload: false` here is paired with a generated `FONT_PRELOADS`
 * instead of leaving `next/font` to emit the links.
 */
const display = Unbounded({
  subsets: ["cyrillic", "latin"],
  weight: ["500", "700", "900"],
  variable: "--font-unbounded",
  preload: false,
});

const sans = Golos_Text({
  subsets: ["cyrillic", "latin"],
  weight: ["400", "500", "600"],
  variable: "--font-golos",
  preload: false,
});

export const FONT_VARIABLES = `${display.variable} ${sans.variable}`;

export const FONT_PRELOADS: readonly string[] = [
  // sync-font-preloads:begin ↓ generated by scripts/sync-font-preloads.mjs
  "/_next/static/media/4e1c87b7aa9e2f2f-s.3o02-8iknf6dl.woff2",
  "/_next/static/media/b4a06a523f527a0e-s.3psl0_mnhzy2y.woff2",
  "/_next/static/media/b59689b1142d37ce-s.1bk8_xp319hr4.woff2",
  "/_next/static/media/cfdfbee4d6cf0a93-s.1jwcpm6w583_v.woff2",
  // sync-font-preloads:end ↑
];
